### ISSUE TITLE
Handle array for admin_email config

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/comment-notifications#49]
Silverstripe allows an 'array style' config for `admin_email` config that includes the 'Name' as well as the 'Email' - https://docs.silverstripe.org/en/4/developer_guides/email/#administrator-emails

```yml
SilverStripe\Control\Email\Email:
  admin_email:
    support@example.com: 'Support team'
```

However this breaks in comment-notifications.  The pull request below fixes this.

### PRs
- https://github.com/silverstripe/comment-notifications/pull/47
OR
- ~~https://github.com/silverstripe/comment-notifications/pull/50~~
- https://github.com/silverstripe/comment-notifications/pull/51
